// Dados de demonstração quando Supabase não está configurado
export const mockJogadores = [
  {
    id: '1',
    nome: 'Carlos Silva',
    posicao: 'Atacante',
    numero: 9,
    foto_url: null,
    gols: 14,
    assistencias: 5,
    jogos: 18,
    vitorias: 12,
    derrotas: 4,
    mvps: 6,
    overall: 91,
  },
  {
    id: '2',
    nome: 'Rafael Lima',
    posicao: 'Meia',
    numero: 10,
    foto_url: null,
    gols: 8,
    assistencias: 13,
    jogos: 18,
    vitorias: 12,
    derrotas: 4,
    mvps: 4,
    overall: 87,
  },
  {
    id: '3',
    nome: 'Diego Costa',
    posicao: 'Atacante',
    numero: 11,
    foto_url: null,
    gols: 10,
    assistencias: 6,
    jogos: 16,
    vitorias: 10,
    derrotas: 5,
    mvps: 3,
    overall: 83,
  },
  {
    id: '4',
    nome: 'Bruno Santos',
    posicao: 'Defensor',
    numero: 4,
    foto_url: null,
    gols: 2,
    assistencias: 4,
    jogos: 17,
    vitorias: 11,
    derrotas: 4,
    mvps: 2,
    overall: 78,
  },
  {
    id: '5',
    nome: 'Marcos Oliveira',
    posicao: 'Goleiro',
    numero: 1,
    foto_url: null,
    gols: 0,
    assistencias: 1,
    jogos: 18,
    vitorias: 12,
    derrotas: 4,
    mvps: 3,
    overall: 76,
  },
  {
    id: '6',
    nome: 'Lucas Ferreira',
    posicao: 'Defensor',
    numero: 5,
    foto_url: null,
    gols: 1,
    assistencias: 3,
    jogos: 15,
    vitorias: 9,
    derrotas: 5,
    mvps: 1,
    overall: 72,
  },
  {
    id: '7',
    nome: 'André Mendes',
    posicao: 'Meia',
    numero: 8,
    foto_url: null,
    gols: 5,
    assistencias: 8,
    jogos: 14,
    vitorias: 8,
    derrotas: 5,
    mvps: 2,
    overall: 74,
  },
  {
    id: '8',
    nome: 'Pedro Alves',
    posicao: 'Atacante',
    numero: 7,
    foto_url: null,
    gols: 6,
    assistencias: 4,
    jogos: 13,
    vitorias: 7,
    derrotas: 5,
    mvps: 1,
    overall: 70,
  },
]

export const mockPartidas = [
  {
    id: '1',
    data: '2024-12-15',
    adversario: 'FC Dragões',
    placar_nos: 3,
    placar_adversario: 1,
    resultado: 'vitoria',
    local: 'Campo Municipal',
  },
  {
    id: '2',
    data: '2024-12-08',
    adversario: 'Unidos FC',
    placar_nos: 2,
    placar_adversario: 2,
    resultado: 'empate',
    local: 'Campo do Adversário',
  },
  {
    id: '3',
    data: '2024-12-01',
    adversario: 'Estrelas do Sul',
    placar_nos: 4,
    placar_adversario: 0,
    resultado: 'vitoria',
    local: 'Campo Municipal',
  },
  {
    id: '4',
    data: '2024-11-24',
    adversario: 'Atlético Centenário',
    placar_nos: 1,
    placar_adversario: 2,
    resultado: 'derrota',
    local: 'Campo do Adversário',
  },
  {
    id: '5',
    data: '2024-11-17',
    adversario: 'Furacão FC',
    placar_nos: 3,
    placar_adversario: 1,
    resultado: 'vitoria',
    local: 'Campo Municipal',
  },
]
